import { useMessage } from 'naive-ui'
import { useAiAnalysisBaseState } from './useAiAnalysisBaseState'
import { useAiAnalysisPanelWiring } from './useAiAnalysisPanelWiring'
import { useAiAnalysisPropRefs } from './useAiAnalysisPropRefs'
import { useAiAnalysisRunnerWiring } from './useAiAnalysisRunnerWiring'
import { useAiAnalysisStateWiring } from './useAiAnalysisStateWiring'
import type { AiAnalysisViewModelProps } from '../viewModelTypes'

export const useAiAnalysisViewModel = (props: AiAnalysisViewModelProps) => {
  const message = useMessage()
  const {
    tasks,
    selectedTask,
    selectedNode,
    selectedFlowItemId,
    loadedTargets,
    loadedDefaultTargetId,
    hasDeferredLoadedTargets,
    ensureLoadedTargets,
  } = useAiAnalysisPropRefs(props)
  const {
    settings,
    apiKey,
    question,
    analyzing,
    analyzingStage,
    testing,
    resultText,
    usageText,
    evidencePanelCollapsed,
    activeRoundQuestion,
    showApiKeyHint,
    globalSettingsCollapsed,
    memoryDialogVisible,
    quickPromptProfileOverride,
    quickPromptFocusOverride,
    streamingRenderText,
    pendingStreamFullText,
    clearStreamFlushTimer,
    flushStreamingText,
  } = useAiAnalysisBaseState()

  const {
    currentContextKey,
    selectedTaskTitle,
    sourceLabel,
    selectedNodeFocusEnabled,
    effectiveSelectedNode,
    effectiveSelectedFlowItemId,
    selectedNodeFocusDetail,
    quickPrompts,
    handleApplyQuickPrompt,
    clearApiKey,
    resetAnalyzeTransientState,
    waitForUiPaint,
    appendUsageNote,
    memoryModeEnabled,
    memoryStateStore,
    conversationTurns,
    lastRequestUsedMemory,
    currentMemoryState,
    currentMemoryFull,
    currentMemoryPreview,
    memoryApplicable,
    memoryStatusText,
    clearMemory,
    clearCurrentTaskMemory,
    conversationView,
    conversationFollowMode,
    renderedResultHtml,
    streamingAnswerHtml,
    showStreamingTurn,
    conversationTurnViews,
    handleExportConversation,
    onErrorPreview,
    anchorPreview,
    jumpBackPreview,
  } = useAiAnalysisStateWiring({
    tasks,
    selectedTask,
    selectedNode,
    selectedFlowItemId,
    loadedTargets,
    loadedDefaultTargetId,
    settings,
    apiKey,
    question,
    quickPromptProfileOverride,
    quickPromptFocusOverride,
    analyzing,
    analyzingStage,
    streamingRenderText,
    pendingStreamFullText,
    clearStreamFlushTimer,
    activeRoundQuestion,
    usageText,
    resultText,
    message,
  })

  const { handleTest, handleAnalyze } = useAiAnalysisRunnerWiring({
    apiKey,
    question,
    settings,
    tasks,
    selectedTask,
    loadedTargets,
    loadedDefaultTargetId,
    hasDeferredLoadedTargets,
    ensureLoadedTargets,
    currentContextKey,
    memoryStateStore,
    memoryModeEnabled,
    conversationTurns,
    quickPromptProfileOverride,
    quickPromptFocusOverride,
    activeRoundQuestion,
    usageText,
    analyzingStage,
    pendingStreamFullText,
    resultText,
    lastRequestUsedMemory,
    selectedNodeFocusEnabled,
    effectiveSelectedNode,
    effectiveSelectedFlowItemId,
    analyzing,
    testing,
    resetAnalyzeTransientState,
    appendUsageNote,
    flushStreamingText,
    waitForUiPaint,
    message,
  })

  const {
    inputPanelProps,
    inputPanelHandlers,
    outputPanelProps,
    outputPanelHandlers,
  } = useAiAnalysisPanelWiring({
    apiKey,
    showApiKeyHint,
    globalSettingsCollapsed,
    testing,
    analyzing,
    question,
    settings,
    memoryModeEnabled,
    memoryApplicable,
    memoryStatusText,
    selectedTaskTitle,
    sourceLabel,
    selectedNodeFocusDetail,
    currentMemoryState,
    currentMemoryPreview,
    quickPrompts,
    usageText,
    onErrorPreview,
    anchorPreview,
    jumpBackPreview,
    evidencePanelCollapsed,
    conversationTurnViews,
    showStreamingTurn,
    conversationFollowMode,
    resultText,
    renderedResultHtml,
    activeRoundQuestion,
    streamingAnswerHtml,
    lastRequestUsedMemory,
    aiOutputScrollbarRef: conversationView.aiOutputScrollbarRef,
    turnListRef: conversationView.turnListRef,
    memoryDialogVisible,
    onHandleTest: handleTest,
    onClearApiKey: clearApiKey,
    onClearCurrentTaskMemory: clearCurrentTaskMemory,
    onClearMemory: clearMemory,
    onHandleApplyQuickPrompt: handleApplyQuickPrompt,
    onHandleAnalyze: handleAnalyze,
    onHandleExportConversation: handleExportConversation,
  })

  return {
    inputPanelProps,
    inputPanelHandlers,
    outputPanelProps,
    outputPanelHandlers,
    memoryDialogVisible,
    currentMemoryFull,
  }
}
