import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * Extract the CHANGELOG.md section for a given release version.
 *
 * Usage:
 *   node scripts/changelog-notes.mjs <version>
 *
 * Prints the section (including the heading) to stdout, or exits non-zero when
 * the version section cannot be found. Used by CI to generate GitHub Release notes.
 *
 * Accepts both "3.6.0" and "v3.6.0", and both heading styles:
 * - ## [3.6.0] - 2026-08-30
 * - ## [v3.6.0](https://.../compare/...) - 2026-08-30
 *
 * Keep a Changelog writes version headings and cross-references as reference-style
 * links ("[3.6.0]") whose definitions live in a block at the end of CHANGELOG.md.
 * Those definitions are not part of a release body, so each reference that has one
 * is resolved to an inline link and the block is dropped. Without this the heading
 * renders as literal "[3.6.0]" text, and extracting the last section pulls the whole
 * definition block into the release notes.
 */

const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const versionArg = process.argv[2]
if (!versionArg) {
  console.error('Usage: node scripts/changelog-notes.mjs <version>')
  process.exit(2)
}

const changelogPath = resolve(import.meta.dirname, '..', 'CHANGELOG.md')
const version = versionArg.startsWith('v') ? versionArg : `v${versionArg}`
const bareVersion = version.replace(/^v/, '')

const changelog = readFileSync(changelogPath, 'utf8').replace(/^\uFEFF/, '')
const lines = changelog.split(/\r?\n/)

const definitionPattern = /^\[([^\]]+)\]:\s+(\S+)\s*$/
const definitions = new Map()
for (const line of lines) {
  const match = definitionPattern.exec(line.trim())
  if (match && !definitions.has(match[1])) definitions.set(match[1], match[2])
}

const headingPattern = /^## \[v?[^\]]+\](?:\([^)]*\))?(?:\s|$)/
const targetPattern = new RegExp(`^## \\[v?${escapeRegex(bareVersion)}\\]`)

const startIndex = lines.findIndex((line) => targetPattern.test(line))
if (startIndex === -1) {
  console.error(`No CHANGELOG section found for ${version} in ${changelogPath}`)
  process.exit(1)
}

const endIndex = lines.findIndex((line, index) => index > startIndex && headingPattern.test(line))
const sectionLines = lines
  .slice(startIndex, endIndex === -1 ? lines.length : endIndex)
  .filter((line) => line.trim() !== '<!-- generated by git-cliff -->')

// Trailing blank lines and link definitions belong to the file, not to the notes.
let end = sectionLines.length
while (end > 0) {
  const line = (sectionLines[end - 1] ?? '').trim()
  if (line !== '' && !definitionPattern.test(line)) break
  end -= 1
}

// Resolve reference-style links that have a definition. The lookahead keeps inline links
// ("[text](url)") and prefix keeps images ("![alt]") untouched.
const section = sectionLines
  .slice(0, end)
  .join('\n')
  .replace(/(!?)\[([^\]]+)\](?!\()/g, (whole, bang, label) => {
    if (bang) return whole
    const url = definitions.get(label)
    return url === undefined ? whole : `[${label}](${url})`
  })
  .trim()

if (!section) {
  console.error(`CHANGELOG section for ${version} is empty`)
  process.exit(1)
}

process.stdout.write(`${section}\n`)
