import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * Extract the CHANGELOG.md section for a given release version.
 *
 * Usage:
 *   node scripts/changelog-notes.mjs <version>
 *
 * Prints the section (including the heading) to stdout, or exits non-zero when
 * the version section cannot be found. Used by CI to generate GitHub Release notes.
 *
 * Accepts both "3.6.0" and "v3.6.0", and both heading styles:
 * - ## [3.6.0] - 2026-08-30
 * - ## [v3.6.0](https://.../compare/...) - 2026-08-30
 */

const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const versionArg = process.argv[2]
if (!versionArg) {
  console.error('Usage: node scripts/changelog-notes.mjs <version>')
  process.exit(2)
}

const changelogPath = resolve(import.meta.dirname, '..', 'CHANGELOG.md')
const version = versionArg.startsWith('v') ? versionArg : `v${versionArg}`
const bareVersion = version.replace(/^v/, '')

const changelog = readFileSync(changelogPath, 'utf8').replace(/^\uFEFF/, '')
const lines = changelog.split(/\r?\n/)

const headingPattern = /^## \[v?[^\]]+\](?:\([^)]*\))?(?:\s|$)/
const targetPattern = new RegExp(`^## \\[v?${escapeRegex(bareVersion)}\\]`)

const startIndex = lines.findIndex((line) => targetPattern.test(line))
if (startIndex === -1) {
  console.error(`No CHANGELOG section found for ${version} in ${changelogPath}`)
  process.exit(1)
}

const endIndex = lines.findIndex((line, index) => index > startIndex && headingPattern.test(line))
const section = lines
  .slice(startIndex, endIndex === -1 ? lines.length : endIndex)
  .filter((line) => line.trim() !== '<!-- generated by git-cliff -->')
  .join('\n')
  .trim()

if (!section) {
  console.error(`CHANGELOG section for ${version} is empty`)
  process.exit(1)
}

process.stdout.write(`${section}\n`)
